### ISSUE TITLE
Revert code to 7dd5cce

### ISSUE THREAD

**Issue by manugarciaquismondo** [ismms-himc/himc_helper_functions#10]
By accident, my branch was overwriting `master`. @cornhundred, please revert code to commit `7dd5cce` (your latest) using `git revert 7dd5cce`,then change the version number and then execute `git commit -m "reverting to previous head of master" && git push`

**Comment by cornhundred** [comment]
@manugarciaquismondo I pulled in your changes, do you think I can close this?

**Comment by cornhundred** [comment]
We did not do this.
