### ISSUE TITLE
Inconsistent gene names / formatting in recent liver sample deliveries

### ISSUE THREAD

**Issue by asmagen** [ismms-himc/himc_helper_functions#20]
Is it possible that the gene names have changed in the most recent datasets? Why would it change at all of it’s the same reference genome? That’s something that shouldn’t have happened as we discussed in the last comp meeting because it breaks existing pipelines. If we end up finding that all of the newly complied liver data conforms to that inconsistent gene annotation then the alignment of the entire cohort will have to be repeated
We don’t have a way to readjust the clustering models to a new gene annotation, it’ll have to be realigned to the old reference
And needless to say, this is urgent and important

**Comment by cornhundred** [comment]
Hi @asmagen could you please give us a little more info. For instance what Gene names are changed?

**Comment by asmagen** [comment]
I’m looking at the files from old and new libraries received from HIMC and the feature matrices are different. Why are you (Manuel via slack) saying they haven’t changed? Moreover, the gene symbols for the same ensembl IDs are inconsistent (not sure if it’s a bug or the actual gene symbol was updated for these genes)

**Comment by cornhundred** [comment]
This is almost certainly an issue with differences in transcriptome versions. I'll reopen if reverting back to the original transcriptome version doesn't work.
